# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true
gem: [jekyll-paginate, jekyll-gists]
# See fix in https://github.com/poole/hyde/issues/118
plugins: [jekyll-paginate]

# Setup
title:           Chunhua Liu 
tagline:          'U. Melb.'
description:      'Postdoc, <a href="https://cis.unimelb.edu.au/">Computing and Information Systems</a> at <a href="https://www.unimelb.edu.au/">the University of Melbourne</a>.'
url:              https://chunhualiu596.github.io/
baseurl:          /

author:
  name:           'Chunhua Liu'
  url:            https://scholar.google.com/citations?user=IvOlenIAAAAJ&hl=en

paginate:         5

# Custom vars

dblp:             https://dblp.org/pid/68/4756.html
gscholar:	  https://scholar.google.com/citations?user=IvOlenIAAAAJ&hl=en
github:           https://github.com/ChunhuaLiu596
  
